<div class="footer-row">
    <footer class="container footer">
        <!-- <p>&copy; Company 2012</p> -->
        <address>
            <span class="first">
                <strong>Lordan &amp; O'Donovan Ltd. Building Contractors</strong>
            </span>
            <span class="extra-767">Company number: 471084</span>
            <span class="extra-979">Telephone: 021 4772740</span>
            <span class="extra-1200">Mobile: 087 3286085</span>
            <span class="extra-1200 last">Email: 
                <a href="mailto:plordan@eircom.net">plordan@eircom.net</a>
            </span>
            <!-- <abbr title="Phone">P:</abbr> (123) 456-7890 -->
        </address>
        <!-- <address>
          <strong>Full Name</strong><br>
          <a href="mailto:#">first.last@gmail.com</a>
        </address> -->
    </footer>
</div>