<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">

<link rel="shortcut icon" href="/favicon.ico?v=2" />

<link rel="stylesheet" href="css/bootstrap.min.css">
<link rel="stylesheet" href="css/bootstrap-responsive.min.css">
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow'>
<link rel="stylesheet" href="css/bootstrap-image-gallery.min.css">
<link rel="stylesheet" href="css/main.css?v3">

<script src="js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>