<div class="header-row">
    <div class="container">
        <div class="navbar">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <h1>
                    <a class="brand" href="index.shtml">
                        Lordan &amp; O'Donovan Ltd. <br/>
                        <span class="tagline">Building Contractors</span>
                    </a>
                </h1>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <!-- <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">All</a></li>
                                <li><a href="#">New Builds</a></li>
                                <li><a href="#">Industrial / Commercial</a></li>
                                <li><a href="#">Revamps</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li> -->
                        <li class="nav-index"><a href="index.shtml">Home</a></li>
                        <li class="nav-projects"><a href="projects.shtml">Projects</a></li>
                        <li class="nav-about"><a href="about.shtml">Company Profile</a></li>
                        <!-- <li class="nav-testimonials"><a href="testimonials.shtml">Testimonials</a></li> -->
                        <li class="nav-references"><a href="references.shtml">References</a></li>
                    </ul>
                    <!-- <form class="navbar-form pull-right">
                        <input class="span2" type="text" placeholder="Email">
                        <input class="span2" type="password" placeholder="Password">
                        <button type="submit" class="btn">Sign in</button>
                    </form> -->
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>
</div>