<div class="span3 feature-box sidebar clearfix">
    <h3>Projects</h3>
    <div class="well">
        <ul class="nav nav-list">
            <li class="nav-header">New Builds</li>
                <li class="clonleigh"><a href="clonleigh.shtml">Private House, Kinsale</a></li>
                <li class="garretstown"><a href="garretstown.shtml">Private House, Garretstown</a></li>
                <!-- <li><a href="project.shtml">Jagoes Mills, Kinsale</a></li> -->
            <li class="nav-header">Industrial / Commercial</li>
                <li class="hilsers-jewellers"><a href="hilsers-jewellers.shtml">Hilsers Jewellers, Bandon</a></li>
                <li class="scannells-pharmacy"><a href="scannells-pharmacy.shtml">Scannells Pharmacy, Bandon</a></li>
                <li class="martin-careys-butchers"><a href="martin-careys-butchers.shtml">Martin Carey Butcher, Bandon</a></li>
                <li class="danielles-restaurant"><a href="danielles-restaurant.shtml">Danielle's Restaurant, Bandon</a></li>
            <li class="nav-header">Revamps</li>
                <li class="timoleague"><a href="timoleague.shtml">Private House, Timoleague</a></li>
                <li class="turners-cross"><a href="turners-cross.shtml">Private House, Turner's Cross</a></li>
                <li class="clonakilty"><a href="clonakilty.shtml">Private House, Clonakilty</a></li>
        </ul>
    </div>
</div>