<div class="span3 feature-box sidebar clearfix">
  <h3>Contact Us</h3>
  <div class="well contact">
    <p>
      <span class="nav-header">Address</span>
      Lordan &amp; O'Donovan Ltd., <br>Jagoes Mills, <br>Kinsale, <br>Co. Cork
    </p>
    <p><span class="nav-header">Phone</span> +353 21 4772740</p>
    <p><span class="nav-header">Mobile</span> +353 87 3286085</p>
    <p><span class="nav-header">Email</span> 
      <a href="mailto:plordan@eircom.net">plordan@eircom.net</a>
    </p>
  </div>
</div>